[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_program = "3o7dXUGpic6U7AsCpEwv4ifVp4w2B4waHk3ScbjT1NU2"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo 'no tests'"

[hooks]
